// Part 2 – uploads + QR + payments + audit + security + assemble
'use strict';
const { f0,f1,f2,ev,pre,url,hdr,guard,jsonBody,req,folder } = require('./gen_p4_part1');
const fs = require('fs');

// ── FOLDER 3: S3 Uploads (Auth Tests) ────────────────────────────
function formItem(name,path,auth,tests){
  return {
    name, event:[ev(tests)],
    request:{
      method:'POST', header: auth?[{key:'Authorization',value:`Bearer {{${auth}}}`}]:[],
      body:{ mode:'formdata', formdata:[{key:'file',type:'text',value:''}] },
      url:url(path)
    }
  };
}
const f3 = folder('03 – S3 Upload Auth Tests',[
  formItem('[NEG] No Auth – Book Cover','//uploads/book-cover',null,[
    `pm.test("401 without auth",()=>pm.response.to.have.status(401));`,
    `pm.test("success false",()=>pm.expect(pm.response.json().success).to.be.false);`,
  ]),
  formItem('[NEG] Customer RBAC – Book Cover','/uploads/book-cover','accessToken',[
    ...guard(['accessToken']),
    `pm.test("403 customer cannot upload",()=>pm.response.to.have.status(403));`,
  ]),
  formItem('[NEG] No Auth – Audio','/uploads/audio',null,[
    `pm.test("401 without auth",()=>pm.response.to.have.status(401));`,
  ]),
  formItem('[REACH] Admin reaches book-cover endpoint','/uploads/book-cover','adminAccessToken',[
    ...guard(['adminAccessToken']),
    `pm.test("Auth passed – endpoint reached (400 no file or 201 with file)",()=>pm.expect(pm.response.code).to.be.oneOf([201,400]));`,
    `pm.test("Returns JSON",()=>pm.expect(pm.response.json()).to.have.property("success"));`,
  ]),
  formItem('[REACH] Admin reaches audio endpoint','/uploads/audio','adminAccessToken',[
    ...guard(['adminAccessToken']),
    `pm.test("Auth passed – endpoint reached",()=>pm.expect(pm.response.code).to.be.oneOf([201,400]));`,
  ]),
]);

// ── FOLDER 4: QR System ───────────────────────────────────────────
const f4 = folder('04 – QR Song System',[
  {
    name:'[GUARD] bookSlug is populated',
    event:[ev([
      `pm.test("bookSlug was generated by Setup folder", ()=>{`,
      `  const s=pm.environment.get("bookSlug");`,
      `  pm.expect(s,"bookSlug is empty – run 02 Data Setup first").to.be.ok;`,
      `  pm.expect(s,"bookSlug looks malformed").to.not.equal("undefined");`,
      `});`,
    ])],
    request:{ method:'GET', header:[], url:url('/health') }
  },
  {
    name:'Get Book by Slug (Public Store)',
    event:[ev([
      ...guard(['bookSlug']),
      `pm.test("200 OK",()=>pm.response.to.have.status(200));`,
      `const d=pm.response.json().data;`,
      `pm.test("Has title",()=>pm.expect(d).to.have.property("title"));`,
      `pm.test("Has author",()=>pm.expect(d).to.have.property("author"));`,
      `pm.test("Has product",()=>pm.expect(d).to.have.property("product"));`,
      `pm.test("Product ACTIVE",()=>pm.expect(d.product.status).to.equal("ACTIVE"));`,
    ])],
    request:{ method:'GET', header:[], url:{ raw:`{{baseUrl}}/books/slug/{{bookSlug}}`, host:['{{baseUrl}}'], path:['books','slug','{{bookSlug}}'] } }
  },
  {
    name:'Get Book QR Data (Public)',
    event:[ev([
      ...guard(['bookSlug']),
      `pm.test("200 OK",()=>pm.response.to.have.status(200));`,
      `const d=pm.response.json().data;`,
      `pm.test("Has title",()=>pm.expect(d).to.have.property("title"));`,
      `pm.test("Has author",()=>pm.expect(d).to.have.property("author"));`,
      `pm.test("qrEnabled is true",()=>pm.expect(d.qrEnabled).to.be.true);`,
      `pm.test("songTitle present",()=>pm.expect(d.songTitle).to.be.a("string"));`,
      `pm.test("songUrl present",()=>pm.expect(d.songUrl).to.be.a("string"));`,
    ])],
    request:{ method:'GET', header:[], url:{ raw:`{{baseUrl}}/books/{{bookSlug}}/qr`, host:['{{baseUrl}}'], path:['books','{{bookSlug}}','qr'] } }
  },
  req('[NEG] QR Non-existent Slug','GET','/books/slug-that-will-never-exist-xyz123/qr',null,null,[ev([
    `pm.test("404 not found",()=>pm.response.to.have.status(404));`,
    `pm.test("success false",()=>pm.expect(pm.response.json().success).to.be.false);`,
  ])]),
  req('[NEG] Book Slug Not Found','GET','/books/slug/slug-that-will-never-exist-xyz123',null,null,[ev([
    `pm.test("404 not found",()=>pm.response.to.have.status(404));`,
  ])]),
]);

// ── FOLDER 5: Payments ────────────────────────────────────────────
const f5 = folder('05 – Razorpay Payments',[
  {
    name:'[GUARD] orderId is populated',
    event:[ev([
      `pm.test("orderId was generated by Checkout", ()=>{`,
      `  const o=pm.environment.get("orderId");`,
      `  pm.expect(o,"orderId is empty – run 02 Checkout Setup first").to.be.ok;`,
      `});`,
    ])],
    request:{ method:'GET', header:[], url:url('/health') }
  },
  {
    name:'Create Razorpay Order',
    event:[ev([
      ...guard(['accessToken','orderId']),
      `const code=pm.response.code;`,
      `pm.test("201 or 503 (no Razorpay creds)",()=>pm.expect(code).to.be.oneOf([201,503,400]));`,
      `if(code===201){`,
      `  const d=pm.response.json().data;`,
      `  pm.environment.set("razorpayOrderId",d.razorpayOrderId||"");`,
      `  pm.test("razorpayOrderId saved",()=>pm.expect(d.razorpayOrderId).to.be.a("string"));`,
      `  pm.test("amount in paise",()=>pm.expect(d.amount).to.be.a("number"));`,
      `  pm.test("currency INR",()=>pm.expect(d.currency).to.equal("INR"));`,
      `  pm.test("key present",()=>pm.expect(d.key).to.be.a("string"));`,
      `} else {`,
      `  pm.test("Service unavailable or not configured – acceptable in dev",()=>true);`,
      `}`
    ])],
    request:{
      method:'POST', header:hdr('accessToken'), url:url('/payments/create-order'),
      body:jsonBody({ orderId:'{{orderId}}' })
    }
  },
  req('[NEG] Verify Invalid Signature','POST','/payments/verify',
    { orderId:'{{orderId}}', razorpayOrderId:'order_FAKE123', razorpayPaymentId:'pay_FAKE123', razorpaySignature:'TAMPERED_SIGNATURE_INVALID' },
    'accessToken',
    [ev([
      ...guard(['accessToken','orderId']),
      `pm.test("400 invalid signature",()=>pm.response.to.have.status(400));`,
      `pm.test("success false",()=>pm.expect(pm.response.json().success).to.be.false);`,
    ])]
  ),
  req('[NEG] Create Order Without Auth','POST','/payments/create-order',
    { orderId:'{{orderId}}' }, null,
    [ev([`pm.test("401 no auth",()=>pm.response.to.have.status(401));`])]
  ),
  req('[NEG] Create Order Missing orderId','POST','/payments/create-order',
    {}, 'accessToken',
    [ev([`pm.test("400 missing orderId",()=>pm.response.to.have.status(400));`])]
  ),
  req('[NEG] Verify Missing Fields','POST','/payments/verify',
    { orderId:'{{orderId}}' }, 'accessToken',
    [ev([`pm.test("400 missing fields",()=>pm.response.to.have.status(400));`])]
  ),
]);

// ── FOLDER 6: Audit Logs ──────────────────────────────────────────
const f6 = folder('06 – Audit Logs',[
  req('List Audit Logs','GET','/admin/audit-logs?page=1&limit=20',null,'adminAccessToken',[ev([
    ...guard(['adminAccessToken']),
    `pm.test("200 OK",()=>pm.response.to.have.status(200));`,
    `const d=pm.response.json().data;`,
    `pm.test("items is array",()=>pm.expect(d.items).to.be.an("array"));`,
    `pm.test("pagination.total exists",()=>pm.expect(d.pagination).to.have.property("total"));`,
    `pm.test("Has audit entries from setup",()=>pm.expect(d.pagination.total).to.be.gte(0));`,
  ])]),
  req('Filter by PRODUCT_CREATE','GET','/admin/audit-logs?action=PRODUCT_CREATE&limit=10',null,'adminAccessToken',[ev([
    `pm.test("200 OK",()=>pm.response.to.have.status(200));`,
    `const items=pm.response.json().data.items;`,
    `pm.test("All items are PRODUCT_CREATE",()=>items.forEach(i=>pm.expect(i.action).to.equal("PRODUCT_CREATE")));`,
  ])]),
  req('Filter by Order entity','GET','/admin/audit-logs?entityType=Order',null,'adminAccessToken',[ev([
    `pm.test("200 OK",()=>pm.response.to.have.status(200));`,
    `const items=pm.response.json().data.items;`,
    `pm.test("All items entityType=Order",()=>items.forEach(i=>pm.expect(i.entityType).to.equal("Order")));`,
  ])]),
  req('Filter PAYMENT_VERIFIED','GET','/admin/audit-logs?action=PAYMENT_VERIFIED',null,'adminAccessToken',[ev([
    `pm.test("200 OK",()=>pm.response.to.have.status(200));`,
    `pm.test("items array",()=>pm.expect(pm.response.json().data.items).to.be.an("array"));`,
  ])]),
  req('[NEG] No Auth','GET','/admin/audit-logs',null,null,[ev([`pm.test("401",()=>pm.response.to.have.status(401));`])]),
  req('[NEG] Customer Auth','GET','/admin/audit-logs',null,'accessToken',[ev([`pm.test("403",()=>pm.response.to.have.status(403));`])]),
]);

// ── FOLDER 7: Security ────────────────────────────────────────────
const f7 = folder('07 – Security Tests',[
  req('[SEC] Admin Route as Customer','GET','/admin/orders',null,'accessToken',[ev([
    ...guard(['accessToken']),
    `pm.test("403 RBAC enforced",()=>pm.response.to.have.status(403));`,
  ])]),
  req('[SEC] No Token','GET','/admin/orders',null,null,[ev([`pm.test("401",()=>pm.response.to.have.status(401));`])]),
  {
    name:'[SEC] Tampered JWT',
    event:[ev([
      `pm.test("401 tampered JWT rejected",()=>pm.response.to.have.status(401));`,
      `pm.test("success false",()=>pm.expect(pm.response.json().success).to.be.false);`,
    ])],
    request:{ method:'GET', header:[{key:'Authorization',value:'Bearer eyJhbGciOiJIUzI1NiJ9.TAMPERED.INVALIDSIG'}], url:url('/auth/me') }
  },
  req('[SEC] XSS in Inquiry','POST','/inquiries',
    { name:'XSS Test', email:'xss@autotest.com', type:'GENERAL', message:"<script>alert('XSS')</script>Hello" },
    null,
    [ev([
      `pm.test("Request accepted – sanitized",()=>pm.expect(pm.response.code).to.be.oneOf([200,201]));`,
      `pm.test("No script tag in response",()=>pm.expect(JSON.stringify(pm.response.json())).to.not.include("<script>"));`,
    ])]
  ),
  req('[SEC] SQL Injection in Search','GET',"/products?search=' OR 1=1--",null,null,[ev([
    `pm.test("Server did not crash",()=>pm.expect(pm.response.code).to.be.oneOf([200,400]));`,
    `pm.test("Valid JSON returned",()=>pm.response.json());`,
  ])]),
  req('[SEC] Payment for Other User Order','POST','/payments/create-order',
    { orderId:'cldoesnotexist0000000000' },'accessToken',
    [ev([
      `pm.test("404 or 400 – cannot access other order",()=>pm.expect(pm.response.code).to.be.oneOf([404,400,422]));`,
      `pm.test("success false",()=>pm.expect(pm.response.json().success).to.be.false);`,
    ])]
  ),
  req('[SEC] No Stack Trace in Error','GET','/nonexistent-route-xyz-abc',null,null,[ev([
    `pm.test("No stack trace in body",()=>{`,
    `  const b=JSON.stringify(pm.response.json());`,
    `  pm.expect(b).to.not.include("at Object.");`,
    `  pm.expect(b).to.not.include("node_modules");`,
    `});`,
  ])]),
]);

// ── ASSEMBLE ──────────────────────────────────────────────────────
const collection = {
  info:{
    name:'VINVERSE Phase 4 – Fully Automated',
    _postman_id:'vinverse-phase4-v3',
    description:'Self-contained. Only set baseUrl + adminEmail + adminPassword collection vars.',
    schema:'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
  },
  variable:[
    { key:'baseUrl', value:'http://localhost:4000/api/v1', type:'default' },
    { key:'adminEmail', value:'admin@vinverse.in', type:'default' },
    { key:'adminPassword', value:'', type:'secret', description:'Set this once – your admin password from bootstrap' },
  ],
  item:[ f0, f1, f2, f3, f4, f5, f6, f7 ]
};

fs.writeFileSync('VINVERSE_PHASE4_POSTMAN_COLLECTION.json', JSON.stringify(collection,null,2));
console.log('✅ Collection generated.');
console.log('\n=== VARIABLE DEPENDENCY REPORT ===');
const report = [
  ['accessToken',       'Register Customer (01)',   'Auth/upload/cart/checkout/payment tests'],
  ['refreshToken',      'Register Customer (01)',   'Stored, not consumed in automated tests'],
  ['userId',            'Register Customer (01)',   'Guard checks + auditActorId fallback'],
  ['adminAccessToken',  'Admin Login (01)',          'All admin endpoints, uploads, audit logs'],
  ['auditActorId',      'Admin Login (01)',          'Filter audit log by actor'],
  ['productId',         'Create Product (02)',       'Add to Cart (02)'],
  ['bookId',            'Create Product (02)',       'Stored for manual use'],
  ['bookSlug',          'Create Product (02)',       'QR folder – book slug + QR endpoints'],
  ['addressId',         'Create Address (02)',       'Checkout (02)'],
  ['cartItemId',        'Add to Cart (02)',          'Stored for manual use'],
  ['orderId',           'Checkout (02)',             'Create Razorpay Order, Verify Payment'],
  ['razorpayOrderId',   'Create Razorpay Order (05)','Verify Payment (05) – if Razorpay configured'],
];
report.forEach(([v,src,used])=>console.log(`  ${v.padEnd(22)} <- ${src.padEnd(30)} -> ${used}`));
