$kind: http-request
url: "{{baseUrl}}/settings"
method: PATCH
body:
  type: json
  content: |-
    {
      "storeName": "VINVERSE PREMIUM"
    }
auth:
  type: bearer
  credentials:
    token: "{{adminAccessToken}}"
scripts:
  - type: afterResponse
    code: |-
      pm.test('Status code is 20X', function () {
          pm.expect(pm.response.code).to.be.oneOf([200, 201, 204]);
      });
      pm.test('Success is true', function () {
          var jsonData = pm.response.json();
          pm.expect(jsonData.success).to.be.true;
      });
      pm.test('Settings update persists', function() { pm.expect(pm.response.json().data.storeName).to.eql('VINVERSE PREMIUM'); });
    language: text/javascript
order: 2000
